// <auto-generated />
using System;
using DrillTestCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DrillTestCore.Migrations
{
    [DbContext(typeof(AliDbContext))]
    [Migration("20200702054933_initmysql")]
    partial class initmysql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DrillTestCore.Models.Holerec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<short>("HoleNumber")
                        .HasColumnType("smallint");

                    b.Property<short?>("LayerNo")
                        .HasColumnType("smallint");

                    b.Property<short?>("MacId")
                        .HasColumnType("smallint");

                    b.Property<float?>("MaxPressure")
                        .HasColumnType("float");

                    b.Property<string>("SerialNo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TestTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Holerecs");
                });

            modelBuilder.Entity("DrillTestCore.Models.Workrec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("HoleCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastTime")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Layer")
                        .HasColumnType("smallint");

                    b.Property<string>("SerialNo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Workrecs");
                });
#pragma warning restore 612, 618
        }
    }
}
